### ISSUE TITLE
multiple "=" symbol in value

### ISSUE THREAD

**Issue by rafuck** [onyx-itdevelopment/onyx-config#2]
I tried to use this library and there was situation with symbol "=" in value of some parameter. I fixed by following changes in function lineToConf(...):
auto sKey = line[0..separatorPos];
auto key = sKey.strip;
	
auto sValue = line[separatorPos+1..$];
auto workLine = sValue.strip;

instead line.split(separator)

**Comment by onyx-itdevelopment** [comment]
Thank. I fix this in new version (v1.2.2).

auto sValue = line[separatorPos+1..$]; - do not work, if separator length > 1 byte

need:
auto workLine = line[separatorPos+separator.length..$].strip;

**Comment by rafuck** [comment]
Yes, of course. I use only '=' as key-value separator. In general case your solution is prefer.
